# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: netsparker-cloud@1
  inputs:
    apiConnection: 'Invicti Connection'
    scanTypes: '2'
    scanWebSites: '947a4906-07f1-4a6f-9a30-b00c02b684e5'
    scanWebSitesProfile: '03dfcd85-818b-4a36-93a4-b00c02b9203a'
